language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t Navanithbs/docker-react -f Dockerfile.dev
script:
  - docker run -e CI=true Navanithbs/docker-react npm run test